### ISSUE TITLE
rotation not working

### ISSUE THREAD

**Issue by zozeei** [Xennis/flutter_map_location#35]
When rotating the map The button position will be moving.

**Comment by Xennis** [comment]
The rotation support was just recently added to flutter_map. It rotates all layers and as far as I know, there is no support yet to avoid that. I guess there is further work required in flutter_map to add better support for that. That nothing we can fix in the plugin itself. That's why rotation is disabled in the examples:

https://github.com/Xennis/flutter_map_location/blob/e9afc03d3351da87ffc01d6e27922b9d1e62fbed/example/lib/pages/default.dart#L34

**Comment by Xennis** [comment]
@zozeei flutter_map adding now support to not rotate certain layers. I've added basic support for it in #43 . PS: That will end up on the `dev` branch because flutter_map did not released a new version yet.
